set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR i686)

set(CROSS_PREFIX i686-elf-)

set(CMAKE_ASM_COMPILER   ${CROSS_PREFIX}as)
set(CMAKE_C_COMPILER     ${CROSS_PREFIX}gcc)
set(CMAKE_CXX_COMPILER   ${CROSS_PREFIX}g++)
set(CMAKE_LINKER         ${CROSS_PREFIX}ld)
set(CMAKE_OBJCOPY        ${CROSS_PREFIX}objcopy)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_FIND_ROOT_PATH ${CROSS_ROOT})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)